#!/usr/bin/env python3
"""
Monthly shortage refill pipeline.

Reads shortage.json created by postprocess.py --clean and appends exactly the
needed number of accepted replacement records per month.

Usage:
  python refill_pipeline.py \
    --shortage ./labeled_final/shortage.json \
    --output   ./labeled_final
"""

import sys
import json
import random
import argparse
import re
from pathlib import Path
from datetime import datetime, timezone
from collections import defaultdict

# Reuse label_pipeline helpers.
sys.path.insert(0, str(Path(__file__).parent))
from label_pipeline import (
    CONFIG, COST,
    load_records,
    process_record,
)
import re as _re

# -- English detection; same conservative logic as postprocess.py ----
_UNICODE_FONT_RANGES = [
    (0x1D400, 0x1D7FF),
    (0xFB00,  0xFB06),
]
_BLOCKED_LANGS = {
    "de", "fr", "ar", "ru", "es", "it",
    "nl", "pt", "pl", "tr", "ko", "ja", "zh-cn", "zh-tw",
}

def is_unicode_font_alpha(c: str) -> bool:
    cp = ord(c)
    for start, end in _UNICODE_FONT_RANGES:
        if start <= cp <= end:
            return True
    return False

def is_meaningless_text(text: str) -> bool:
    stripped = text.strip()
    if not stripped:
        return True
    total_alpha = sum(1 for c in stripped if c.isalpha())
    if total_alpha < 5:
        return True
    unicode_font = sum(1 for c in stripped if is_unicode_font_alpha(c))
    if unicode_font / max(len(stripped), 1) > 0.3:
        return True
    return False

def is_english(text: str, threshold: float = 0.7) -> bool:
    if not text or not text.strip():
        return True
    if is_meaningless_text(text):
        return True
    if len(text.strip()) < 20:
        return True
    try:
        from langdetect import detect_langs
        results = detect_langs(text)
        if not results:
            return True
        top = results[0]
        if top.lang in _BLOCKED_LANGS and top.prob >= 0.80:
            return False
    except Exception:
        pass
    return True

def has_mass_mention(text: str, threshold: int = 3) -> bool:
    mentions = _re.findall(r"@[\w.]+", text or "")
    return len(mentions) >= threshold

DATASET_DIRS = CONFIG["input_dirs"]


# ════════════════════════════════════════════════════════════════
#  Utilities
# ════════════════════════════════════════════════════════════════

def get_month(record: dict) -> str:
    val = (record.get("original_post") or {}).get("created_at", "")
    if not val:
        val = record.get("created_at", "")
    if val:
        try:
            ts = float(val)
            return datetime.fromtimestamp(ts, tz=timezone.utc).strftime("%Y-%m")
        except (ValueError, TypeError):
            if len(str(val)) >= 7:
                return str(val)[:7]
    return "unknown"


def load_existing_uids(jsonl_path: Path) -> set:
    uids = set()
    if not jsonl_path.exists():
        return uids
    with open(jsonl_path, encoding="utf-8") as f:
        for line in f:
            line = line.strip()
            if line:
                try:
                    uids.add(json.loads(line).get("uid", ""))
                except Exception:
                    pass
    return uids


# ════════════════════════════════════════════════════════════════
#  Main
# ════════════════════════════════════════════════════════════════

def main():
    parser = argparse.ArgumentParser(description="Refill monthly shortages")
    parser.add_argument("--shortage", required=True,
                        help="Path to shortage.json generated by postprocess.py")
    parser.add_argument("--output",   default="./labeled_final",
                        help="Output folder; appends to existing labeled_memes.jsonl")
    parser.add_argument("--input",    default=None, nargs="+",
                        help="Input dataset folders (default: CONFIG input_dirs)")
    args = parser.parse_args()

    # Load shortage report.
    shortage_path = Path(args.shortage)
    if not shortage_path.exists():
        print(f"[ERROR] shortage.json not found: {shortage_path}")
        print("  Run python postprocess.py --clean first.")
        return

    shortage_data = json.loads(shortage_path.read_text(encoding="utf-8"))
    shortage      = shortage_data["shortage"]  # {month: count}
    monthly_target = shortage_data["monthly_target"]

    print(f"[LOAD] shortage.json")
    print(f"  Generated at: {shortage_data['generated_at'][:16]}")
    print(f"  Short months: {len(shortage)}")
    print(f"  Total shortfall: {shortage_data['total_short']:,}\n")

    # Output setup.
    output_dir  = Path(args.output)
    output_dir.mkdir(parents=True, exist_ok=True)
    output_jsonl = output_dir / "labeled_memes.jsonl"

    # Load existing UIDs to avoid duplicates.
    print("[LOAD] Loading existing UIDs...")
    existing_uids = load_existing_uids(output_jsonl)
    print(f"  Existing processed UIDs: {len(existing_uids):,}\n")

    # Input folders.
    input_dirs = args.input if args.input else CONFIG["input_dirs"]

    # Group all candidate records by month.
    print("[LOAD] Grouping records by month...")
    all_records = load_records(input_dirs)
    print(f"  Total records: {len(all_records):,}")

    by_month = defaultdict(list)
    for r in all_records:
        uid = r.get("uid", "")
        if uid in existing_uids:
            continue  # Skip records already processed.
        month = get_month(r)
        if month not in shortage:
            continue  # Skip months that do not need refills.
        # Fast mass-mention filter; langdetect runs at processing time.
        orig_text = (r.get("original_post") or {}).get("text") or ""
        if has_mass_mention(orig_text):
            continue
        by_month[month].append(r)

    # Shuffle within each month.
    for m in by_month:
        random.shuffle(by_month[m])

    print(f"\n{'='*58}")
    print("  Refill start")
    print(f"{'='*58}")

    success_by_month = defaultdict(int)
    skipped_validation = 0
    total_success = 0

    with open(output_jsonl, "a", encoding="utf-8") as out_f:
        for month, needed in sorted(shortage.items()):
            candidates = by_month.get(month, [])
            print(f"\n  [{month}] needed: {needed:,} / candidates: {len(candidates):,}")

            if not candidates:
                print(f"  [{month}] no candidates; skipping")
                continue

            for record in candidates:
                if success_by_month[month] >= needed:
                    print(f"  [{month}] reached target: {needed:,}")
                    break

                uid = record.get("uid", "unknown")

                # Run langdetect at processing time.
                orig_text   = (record.get("original_post") or {}).get("text") or ""
                parent_text = (record.get("parent_reply") or {}).get("text") or ""
                meme_text   = (record.get("meme_reply") or {}).get("text") or ""
                if not all(is_english(t) for t in [orig_text, parent_text, meme_text] if t.strip()):
                    continue

                print(f"    [{month} {success_by_month[month]+1}/{needed}] {uid[:30]}")

                try:
                    result = process_record(record, output_dir)
                    if result is None:
                        skipped_validation += 1
                        continue

                    out_f.write(
                        json.dumps(result, ensure_ascii=False, default=str) + "\n"
                    )
                    out_f.flush()

                    # Save an individual record.
                    record_path = output_dir / "records" / f"{uid}.json"
                    record_path.parent.mkdir(exist_ok=True)
                    record_path.write_text(
                        json.dumps(result, ensure_ascii=False, indent=2, default=str),
                        encoding="utf-8"
                    )

                    existing_uids.add(uid)
                    success_by_month[month] += 1
                    total_success += 1

                except Exception as e:
                    import traceback
                    print(f"    [ERROR] {e}\n{traceback.format_exc()}")

            if success_by_month[month] < needed:
                print(f"  [{month}] candidates exhausted: collected {success_by_month[month]}/{needed}")

    # Summary.
    print(f"\n{'='*58}")
    print("  Refill complete")
    print(f"{'='*58}")
    print(f"  Success:              {total_success:,}")
    print(f"  Validation failures:  {skipped_validation:,}")
    print("\n  Monthly refill result:")
    for month in sorted(shortage.keys()):
        needed  = shortage[month]
        got     = success_by_month[month]
        flag    = "OK" if got >= needed else "SHORT"
        print(f"    {month}: {got:,}/{needed:,} {flag}")
    print(f"\n  Output: {output_dir.resolve()}")
    print("\n  [API cost]")
    print(COST.summary())
    print(f"{'='*58}")


if __name__ == "__main__":
    main()
